FROM ubuntu:20.04


RUN apt-get update -y && \
    apt-get install -y python3 python3-pip

WORKDIR /usr/src/app

COPY ./requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./app.py .

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]